### ISSUE TITLE
Automatically switch the query browser to chrome

### ISSUE THREAD

**Issue by sephony** [Garulf/Browser-History#19]
# error
i only have Edge on my computer, so i change the default browser to Edge, but when I click on the query result option with the mouse, the browser is switched to Chrome and an error is reported.
![image](https://github.com/Garulf/Browser-History/assets/111299702/37feef35-5d0d-41e5-85a5-347c1dad9bf3)

![image](https://github.com/Garulf/Browser-History/assets/111299702/33940649-8dc5-4653-b53b-75a41b2e8e33)

# information about error

Flow Launcher version: 1.16.2
OS Version: 19045.3803
IntPtr Length: 8
x64: True

Python Path: D:\anaconda3\pythonw.exe
Node Path: D:\nvm\v20.10.0\node.exe
Date: 12/13/2023 15:23:27
Exception:
Browser History Exception: 
Websites: https://github.com/Garulf/browser-history
Author: Garulf
Version: 0.4.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Exception ignored in: <function Base.__del__ at 0x000002231BD63EC0>
Traceback (most recent call last):
  File "D:\Scoop\apps\Flow-Launcher\current\app-1.16.2\UserData\Plugins\Browser History-0.4.0\plugin\browsers.py", line 39, in __del__
    os.remove(self.temp_path)
PermissionError: [WinError 32] ��һ����������ʹ�ô��ļ��������޷����ʡ�: 'C:\\Users\\User\\AppData\\Local\\Temp\\History'

 ---> System.IO.InvalidDataException: Exception ignored in: <function Base.__del__ at 0x000002231BD63EC0>
Traceback (most recent call last):
  File "D:\Scoop\apps\Flow-Launcher\current\app-1.16.2\UserData\Plugins\Browser History-0.4.0\plugin\browsers.py", line 39, in __del__
    os.remove(self.temp_path)
PermissionError: [WinError 32] ��һ����������ʹ�ô��ļ��������޷����ʡ�: 'C:\\Users\\User\\AppData\\Local\\Temp\\History'

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 297
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 297
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 313
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 849
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 850
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by z1nc0r3** [comment]
Do you have **Ransomware Protection** turned on or any permission issues with the FL? What is the default browser that you have set on FL settings?

![image](https://github.com/Garulf/Browser-History/assets/64279853/d01d019d-5e02-4b86-b54d-a2c5821f8475)

**Comment by Garulf** [comment]
Flow Launcher has changed how it's setting are saved a this plugin does not handle the new way yet.

**Comment by sephony** [comment]
> Do you have **Ransomware Protection** turned on or any permission issues with the FL? What is the default browser that you have set on FL settings?
> 
> ![image](https://private-user-images.githubusercontent.com/64279853/301985889-d01d019d-5e02-4b86-b54d-a2c5821f8475.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMjM1NDAsIm5iZiI6MTcwNzAyMzI0MCwicGF0aCI6Ii82NDI3OTg1My8zMDE5ODU4ODktZDAxZDAxOWQtNWUwMi00Yjg2LWI1NGQtYTJjNTgyMWY4NDc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDA1MDcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNmJlMGJlMDg4ODU5M2Q3MWQ3YWJhMWQxOTk3OTNiYzg2NjljM2QzOWJjNzFjN2ZhMGQ2NTVlNTg5OTZmOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h5ZIZ1eEovo3UnA4ACsd_MKKY3BykRdC60EECrvaE_o)

the FL default browser option i choose is "default" and system default browser is Edge, maybe it's the problem with FL
